### ISSUE TITLE
Traduzir a galeria

### ISSUE THREAD

**Issue by GHolanda14** [lanamesquita/ufc2020.2-gc#31]
A pagina galeria está com algumas partes em inglês.

**Comment by lanamesquita** [comment]
Ótimo Gabriel! Aguardo o PR para corrigir a issue. 😉

**Comment by GHolanda14** [comment]
Eu enviei o PR já, dá uma olhada!

**Comment by lanamesquita** [comment]
Verdade, acabei deixando passar o PR. Mas aceitei lá e já fechou aqui. Muito bom colocar o "close" na descrição. Automatiza o processo.

**Comment by GHolanda14** [comment]
Eu botei closes, achei q era com o s no final, mas é só Close mesmo né? Fica o aprendizado aí kkkkk

**Comment by lanamesquita** [comment]
Tanto faz... ->

https://docs.github.com/pt/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
